"use client";
// /* *
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/7WgiXFTKgG0
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Libre_Franklin } from 'next/font/google'
// import { Archivo } from 'next/font/google'

// libre_franklin({
//   subsets: ['latin'],
//   display: 'swap',
// })

// archivo({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"
// import { JSX, SVGProps } from "react"

// export function Landing() {
//   return (
//     <div className="flex flex-col min-h-[100dvh]">
//       <header className="px-4 lg:px-6 h-14 flex items-center">
//         <Link href="#" className="flex items-center justify-center" prefetch={false}>
//           <MountainIcon className="h-6 w-6" />
//           <span className="sr-only">Recruit</span>
//         </Link>
//         <nav className="ml-auto flex gap-4 sm:gap-6">
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Features
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Pricing
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             About
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Contact
//           </Link>
//           <Link
//             href="#"
//             className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//             prefetch={false}
//           >
//             Sign In
//           </Link>
//         </nav>
//       </header>
//       <main className="flex-1">
//         <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
//           <div className="container px-4 md:px-6">
//               <div className="flex flex-col justify-center space-y-4 mb-6">
//                 <div className="space-y-2">
//                   <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
//                     Recruit the Best Talent for Your Organization
//                   </h1>
//                   <p className="max-w-[600px] text-muted-foreground md:text-xl">
//                     Our recruiting platform helps college organizations and startups connect with the right candidates
//                     on a deeper level, beyond traditional job boards.
//                   </p>
//                 </div>
//                 <div className="flex flex-col gap-2 min-[400px]:flex-row">
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}
//                   >
//                     Sign Up
//                   </Link>
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}
//                   >
//                     Learn More
//                   </Link>
//                 </div>
//               </div>
//               <div className="flex flex-col justify-center space-y-4">
//                 <div className="space-y-2">
//                   <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Why Choose Recruit?</h2>
//                   <p className="text-muted-foreground md:text-xl">
//                     Discover the key benefits of our recruiting platform.
//                   </p>
//                 </div>
//                 <ul className="grid gap-6">
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Comprehensive Profiles</h3>
//                       <p className="text-muted-foreground">
//                         Get a detailed view of each applicant's qualifications, experience, and interests.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Streamlined Tracking</h3>
//                       <p className="text-muted-foreground">
//                         Easily manage the entire application process, from initial submission to final decision.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Collaborative Hiring</h3>
//                       <p className="text-muted-foreground">
//                         Involve your team in the hiring process and make informed decisions together.
//                       </p>
//                     </div>
//                   </li>
//                 </ul>
//               </div>
//             </div>
//         </section>
//         <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
//           <div className="container px-4 md:px-6">
//             <div className="flex flex-col items-center justify-center space-y-4 text-center">
//               <div className="space-y-2">
//                 <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Applicant Management</div>
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Streamline Your Recruiting Process</h2>
//                 <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                   Our platform provides advanced tools to help you manage applications, track candidates, and make
//                   informed hiring decisions.
//                 </p>
//               </div>
//             </div>
//             <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
//               <div className="flex flex-col justify-center space-y-4">
//                 <ul className="grid gap-6">
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Candidate Profiles</h3>
//                       <p className="text-muted-foreground">
//                         Get a comprehensive view of each applicant's qualifications, experience, and interests.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Application Tracking</h3>
//                       <p className="text-muted-foreground">
//                         Easily manage the entire application process, from initial submission to final decision.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Collaborative Hiring</h3>
//                       <p className="text-muted-foreground">
//                         Involve your team in the hiring process and make informed decisions together.
//                       </p>
//                     </div>
//                   </li>
//                 </ul>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section className="w-full py-12 md:py-24 lg:py-32 border-t">
//           <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
//             <div className="space-y-3">
//               <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Simplify your Org&apos;s Recruitment Today 👇</h2>
//               <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                 Sign up today and start connecting with the best talent for your organization.
//               </p>
//             </div>
//             <div className="mx-auto w-full max-w-sm flex flex-col gap-2">
//               <Link
//                 href="#"
//                 className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                 prefetch={false}
//               >
//                 Sign Up
//               </Link>
//               <Link
//                 href="#"
//                 className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                 prefetch={false}
//               >
//                 Sign In
//               </Link>
//             </div>
//           </div>
//         </section>
//       </main>
//       <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
//         <p className="text-xs text-muted-foreground">&copy; 2024 Recruit. All rights reserved.</p>
//         <nav className="sm:ml-auto flex gap-4 sm:gap-6">
//           <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
//             Terms of Service
//           </Link>
//           <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
//             Privacy
//           </Link>
//         </nav>
//       </footer>
//     </div>
//   )
// }

// export function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
//     </svg>
//   )
// }

//components/landing.tsx
import Link from "next/link";
import { Button } from "./ui/button";
import Profile from "./Profile";
import useUser from "@/app/hook/useUser";
import Navbar from "./NavBar";
import { HeroGeometric } from "@/components/ui/shape-landing-hero";
import { FeaturesSectionWithHoverEffects } from "./ui/feature-section-with-hover-effects";
import { motion } from "framer-motion";
import React, { useEffect, useState } from "react";

function LandingAnimatedSections() {
  return (
    <>
      {/* Hero Section */}
      <HeroGeometric
        badge="Recruitment Platform"
        title1="Recruit the Best Talent"
        title2="For Your Organization"
      />
      {/* Features Section */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        viewport={{ once: true }}
        className="w-full flex justify-center py-16"
      >
        <div className="relative max-w-6xl w-full rounded-3xl bg-gradient-to-br from-white/5 via-blue-500/5 to-green-500/5 border border-blue-500/10 backdrop-blur-xl shadow-2xl p-8 md:p-16">
          <FeaturesSectionWithHoverEffects />
        </div>
      </motion.section>
      {/* Process/Stepper Section */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.2 }}
        viewport={{ once: true }}
        className="w-full flex justify-center py-16"
      >
        <div className="relative max-w-4xl w-full rounded-3xl bg-gradient-to-br from-white/5 via-blue-500/5 to-green-500/5 border border-green-500/10 backdrop-blur-xl shadow-2xl p-8 md:p-16 flex flex-col items-center">
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mb-8 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400">
            How Recruitify Works
          </h2>
          <div className="w-full max-w-3xl flex flex-col gap-6">
            {/* Step 1 */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-[#030303]/60 shadow border border-green-400/10">
              <div className="flex items-center justify-center h-10 w-10 rounded-full bg-gradient-to-br from-green-400 to-blue-400 text-white font-bold text-lg shrink-0">
                1
              </div>
              <div>
                <h3 className="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400 mb-1">
                  Create Organization & Invite Board
                </h3>
                <p className="text-sm text-muted-foreground">
                  Set up your club, org, or startup and invite all board members
                  and recruiting managers.
                </p>
              </div>
            </div>
            {/* Step 2 */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-[#030303]/60 shadow border border-green-400/10">
              <div className="flex items-center justify-center h-10 w-10 rounded-full bg-gradient-to-br from-green-400 to-blue-400 text-white font-bold text-lg shrink-0">
                2
              </div>
              <div>
                <h3 className="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400 mb-1">
                  Set Up Recruitment Cycle & Rounds
                </h3>
                <p className="text-sm text-muted-foreground">
                  Create a recruitment cycle (semester, year, etc.) and define
                  rounds (interviews, events) with custom metrics.
                </p>
              </div>
            </div>
            {/* Step 3 */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-[#030303]/60 shadow border border-green-400/10">
              <div className="flex items-center justify-center h-10 w-10 rounded-full bg-gradient-to-br from-green-400 to-blue-400 text-white font-bold text-lg shrink-0">
                3
              </div>
              <div>
                <h3 className="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400 mb-1">
                  Import Applicants via CSV
                </h3>
                <p className="text-sm text-muted-foreground">
                  Upload applicants from your form (Google Forms, Tally, etc.)
                  and map their info instantly.
                </p>
              </div>
            </div>
            {/* Step 4 */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-[#030303]/60 shadow border border-green-400/10">
              <div className="flex items-center justify-center h-10 w-10 rounded-full bg-gradient-to-br from-green-400 to-blue-400 text-white font-bold text-lg shrink-0">
                4
              </div>
              <div>
                <h3 className="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400 mb-1">
                  Collect Feedback & Scores
                </h3>
                <p className="text-sm text-muted-foreground">
                  Gather anonymized or named feedback and scores from board and
                  general members for each round.
                </p>
              </div>
            </div>
            {/* Step 5 */}
            <div className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-[#030303]/60 shadow border border-green-400/10">
              <div className="flex items-center justify-center h-10 w-10 rounded-full bg-gradient-to-br from-green-400 to-blue-400 text-white font-bold text-lg shrink-0">
                5
              </div>
              <div>
                <h3 className="text-lg font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400 mb-1">
                  Progress Applicants & Export Decisions
                </h3>
                <p className="text-sm text-muted-foreground">
                  Move applicants to the next round, mark as
                  accepted/rejected/maybe, and export decisions and emails.
                </p>
              </div>
            </div>
          </div>
        </div>
      </motion.section>
      {/* CTA Section */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.4 }}
        viewport={{ once: true }}
        className="w-full flex justify-center py-16"
      >
        <div className="relative max-w-2xl w-full mx-auto rounded-3xl p-10 bg-gradient-to-br from-white/10 via-blue-500/10 to-green-500/10 shadow-xl border border-green-500/20 backdrop-blur-lg flex flex-col items-center text-center">
          <div className="absolute -inset-1 rounded-3xl bg-gradient-to-br from-green-500/20 via-blue-500/10 to-transparent blur-2xl pointer-events-none" />
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4 bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-400">
            Manage Your Club or Org&apos;s Recruitment—All in One Place
          </h2>
          <p className="text-lg light:text-black dark:text-white mb-8 max-w-xl">
            Recruitify is built for recruiting chairs and boards who need to run
            collaborative, multi-round recruitment cycles. No job boards, no
            applicant portals—just powerful tools for your team.
          </p>
          <div className="flex flex-col gap-3 w-full max-w-xs">
            <Link
              href="/auth?next=/dash"
              className="inline-flex h-12 items-center justify-center rounded-xl bg-gradient-to-r from-green-400 to-blue-500 text-lg font-semibold text-[#030303] shadow-lg transition-transform hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400"
              prefetch={false}
            >
              Get Started
            </Link>
            <Link
              href="/auth?next=/dash"
              className="inline-flex h-12 items-center justify-center rounded-xl border border-black bg-white/10 text-lg font-semibold light:text-black dark:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400"
              prefetch={false}
            >
              Learn More
            </Link>
          </div>
        </div>
      </motion.section>
    </>
  );
}

// Animated, angled, blurred geometric shapes background
function AnimatedShapesBackground() {
  return (
    <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
      {/* Top left indigo shape */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          duration: 1.2,
          delay: 0.3,
          ease: [0.23, 0.86, 0.39, 0.96],
        }}
        className="absolute left-[-10%] md:left-[-5%] top-[15%] md:top-[20%]"
        style={{ width: 600, height: 140 }}
      >
        <motion.div
          initial={{ y: -40, rotate: -3 }}
          animate={{ y: 8, rotate: 5 }}
          transition={{
            duration: 1.6,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
            delay: 0,
          }}
          className="absolute inset-0 w-full h-full"
        >
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-indigo-500/[0.15] to-transparent backdrop-blur-[2px] border-2 border-white/[0.15] shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]" />
        </motion.div>
      </motion.div>
      {/* Top right rose shape */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          duration: 1.2,
          delay: 0.5,
          ease: [0.23, 0.86, 0.39, 0.96],
        }}
        className="absolute right-[-5%] md:right-[0%] top-[70%] md:top-[75%]"
        style={{ width: 500, height: 120 }}
      >
        <motion.div
          initial={{ y: -30, rotate: 0 }}
          animate={{ y: -10, rotate: -6 }}
          transition={{
            duration: 1.7,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
            delay: 0,
          }}
          className="absolute inset-0 w-full h-full"
        >
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-rose-500/[0.15] to-transparent backdrop-blur-[2px] border-2 border-white/[0.15] shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]" />
        </motion.div>
      </motion.div>
      {/* Bottom left violet shape */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          duration: 1.2,
          delay: 0.4,
          ease: [0.23, 0.86, 0.39, 0.96],
        }}
        className="absolute left-[5%] md:left-[10%] bottom-[5%] md:bottom-[10%]"
        style={{ width: 300, height: 80 }}
      >
        <motion.div
          initial={{ y: 30, rotate: 0 }}
          animate={{ y: 12, rotate: -4 }}
          transition={{
            duration: 1.5,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
            delay: 0,
          }}
          className="absolute inset-0 w-full h-full"
        >
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-violet-500/[0.15] to-transparent backdrop-blur-[2px] border-2 border-white/[0.15] shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]" />
        </motion.div>
      </motion.div>
      {/* Top right amber shape */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          duration: 1.2,
          delay: 0.6,
          ease: [0.23, 0.86, 0.39, 0.96],
        }}
        className="absolute right-[15%] md:right-[20%] top-[10%] md:top-[15%]"
        style={{ width: 200, height: 60 }}
      >
        <motion.div
          initial={{ y: -20, rotate: 0 }}
          animate={{ y: 7, rotate: 8 }}
          transition={{
            duration: 1.4,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
            delay: 0,
          }}
          className="absolute inset-0 w-full h-full"
        >
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-amber-500/[0.15] to-transparent backdrop-blur-[2px] border-2 border-white/[0.15] shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]" />
        </motion.div>
      </motion.div>
      {/* Top left cyan shape */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{
          duration: 1.2,
          delay: 0.7,
          ease: [0.23, 0.86, 0.39, 0.96],
        }}
        className="absolute left-[20%] md:left-[25%] top-[5%] md:top-[10%]"
        style={{ width: 150, height: 40 }}
      >
        <motion.div
          initial={{ y: -14, rotate: 0 }}
          animate={{ y: -8, rotate: -3 }}
          transition={{
            duration: 1.3,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
            delay: 0,
          }}
          className="absolute inset-0 w-full h-full"
        >
          <div className="absolute inset-0 rounded-full bg-gradient-to-r from-cyan-500/[0.15] to-transparent backdrop-blur-[2px] border-2 border-white/[0.15] shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]" />
        </motion.div>
      </motion.div>
    </div>
  );
}

export default function Landing() {
  return (
    <div className="relative flex flex-col min-h-screen overflow-x-hidden">
      <AnimatedShapesBackground />
      <header className="relative z-10 px-0 lg:px-6">
        <Navbar />
      </header>
      <main className="flex-1 relative z-10">
        <LandingAnimatedSections />
      </main>
      {/* Footer */}
      <footer className="relative z-10 flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-blue-500/20 backdrop-blur-md bg-white/60 dark:bg-[#030303]/60">
        <p className="text-xs text-neutral-600 dark:text-white/60">
          &copy; 2024 Recruit. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4 text-blue-400"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="/privacy-policy"
            className="text-xs hover:underline underline-offset-4 text-green-400"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}
