"use client";
// /* *
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/7WgiXFTKgG0
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Libre_Franklin } from 'next/font/google'
// import { Archivo } from 'next/font/google'

// libre_franklin({
//   subsets: ['latin'],
//   display: 'swap',
// })

// archivo({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"
// import { JSX, SVGProps } from "react"

// export function Landing() {
//   return (
//     <div className="flex flex-col min-h-[100dvh]">
//       <header className="px-4 lg:px-6 h-14 flex items-center">
//         <Link href="#" className="flex items-center justify-center" prefetch={false}>
//           <MountainIcon className="h-6 w-6" />
//           <span className="sr-only">Recruit</span>
//         </Link>
//         <nav className="ml-auto flex gap-4 sm:gap-6">
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Features
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Pricing
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             About
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Contact
//           </Link>
//           <Link
//             href="#"
//             className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//             prefetch={false}
//           >
//             Sign In
//           </Link>
//         </nav>
//       </header>
//       <main className="flex-1">
//         <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
//           <div className="container px-4 md:px-6">
//               <div className="flex flex-col justify-center space-y-4 mb-6">
//                 <div className="space-y-2">
//                   <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
//                     Recruit the Best Talent for Your Organization
//                   </h1>
//                   <p className="max-w-[600px] text-muted-foreground md:text-xl">
//                     Our recruiting platform helps college organizations and startups connect with the right candidates
//                     on a deeper level, beyond traditional job boards.
//                   </p>
//                 </div>
//                 <div className="flex flex-col gap-2 min-[400px]:flex-row">
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}
//                   >
//                     Sign Up
//                   </Link>
//                   <Link
//                     href="#"
//                     className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                     prefetch={false}
//                   >
//                     Learn More
//                   </Link>
//                 </div>
//               </div>
//               <div className="flex flex-col justify-center space-y-4">
//                 <div className="space-y-2">
//                   <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Why Choose Recruit?</h2>
//                   <p className="text-muted-foreground md:text-xl">
//                     Discover the key benefits of our recruiting platform.
//                   </p>
//                 </div>
//                 <ul className="grid gap-6">
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Comprehensive Profiles</h3>
//                       <p className="text-muted-foreground">
//                         Get a detailed view of each applicant's qualifications, experience, and interests.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Streamlined Tracking</h3>
//                       <p className="text-muted-foreground">
//                         Easily manage the entire application process, from initial submission to final decision.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Collaborative Hiring</h3>
//                       <p className="text-muted-foreground">
//                         Involve your team in the hiring process and make informed decisions together.
//                       </p>
//                     </div>
//                   </li>
//                 </ul>
//               </div>
//             </div>
//         </section>
//         <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
//           <div className="container px-4 md:px-6">
//             <div className="flex flex-col items-center justify-center space-y-4 text-center">
//               <div className="space-y-2">
//                 <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Applicant Management</div>
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Streamline Your Recruiting Process</h2>
//                 <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                   Our platform provides advanced tools to help you manage applications, track candidates, and make
//                   informed hiring decisions.
//                 </p>
//               </div>
//             </div>
//             <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
//               <div className="flex flex-col justify-center space-y-4">
//                 <ul className="grid gap-6">
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Candidate Profiles</h3>
//                       <p className="text-muted-foreground">
//                         Get a comprehensive view of each applicant's qualifications, experience, and interests.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Application Tracking</h3>
//                       <p className="text-muted-foreground">
//                         Easily manage the entire application process, from initial submission to final decision.
//                       </p>
//                     </div>
//                   </li>
//                   <li>
//                     <div className="grid gap-1">
//                       <h3 className="text-xl font-bold">Collaborative Hiring</h3>
//                       <p className="text-muted-foreground">
//                         Involve your team in the hiring process and make informed decisions together.
//                       </p>
//                     </div>
//                   </li>
//                 </ul>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section className="w-full py-12 md:py-24 lg:py-32 border-t">
//           <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
//             <div className="space-y-3">
//               <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Simplify your Org&apos;s Recruitment Today 👇</h2>
//               <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                 Sign up today and start connecting with the best talent for your organization.
//               </p>
//             </div>
//             <div className="mx-auto w-full max-w-sm flex flex-col gap-2">
//               <Link
//                 href="#"
//                 className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                 prefetch={false}
//               >
//                 Sign Up
//               </Link>
//               <Link
//                 href="#"
//                 className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                 prefetch={false}
//               >
//                 Sign In
//               </Link>
//             </div>
//           </div>
//         </section>
//       </main>
//       <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
//         <p className="text-xs text-muted-foreground">&copy; 2024 Recruit. All rights reserved.</p>
//         <nav className="sm:ml-auto flex gap-4 sm:gap-6">
//           <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
//             Terms of Service
//           </Link>
//           <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
//             Privacy
//           </Link>
//         </nav>
//       </footer>
//     </div>
//   )
// }

// export function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
//     </svg>
//   )
// }

//components/landing.tsx
import Link from "next/link";
import Navbar from "./NavBar";
import { HeroGeometric } from "@/components/ui/shape-landing-hero";
import { FeaturesSectionWithHoverEffects } from "./ui/feature-section-with-hover-effects";
import { motion } from "framer-motion";
import React, { useEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

function LandingAnimatedSections() {
  const stepsRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!stepsRef.current) return;

    const ctx = gsap.context(() => {
      const line =
        stepsRef.current?.querySelector<HTMLElement>("[data-how-line]");
      if (!line) return;

      // Fill line from top to bottom in sync with scroll (no card in/out animation)
      gsap.fromTo(
        line,
        { scaleY: 0, transformOrigin: "top center" },
        {
          scaleY: 1,
          ease: "none",
          scrollTrigger: {
            trigger: stepsRef.current,
            start: "top 70%",
            end: "bottom 30%",
            scrub: true,
          },
        },
      );
    }, stepsRef);

    return () => ctx.revert();
  }, []);

  return (
    <>
      {/* Hero Section */}
      <HeroGeometric
        badge="Recruitment Platform"
        title1="Run Better Recruitment"
        title2="For Your Organization"
      />
      {/* Process/Stepper Section */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, delay: 0.1 }}
        viewport={{ once: true, amount: 0.2 }}
        className="w-full flex justify-center items-stretch min-h-screen pt-14 md:pt-20 pb-0"
        id="how-it-works"
      >
        <div
          ref={stepsRef}
          className="relative max-w-5xl w-full rounded-3xl p-8 md:p-14 md:pb-24 ink-card dark:ink-card-dark"
        >
          <div className="flex flex-col items-center text-center mb-10">
            <h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight text-neutral-950 dark:text-white">
              How Recruitify Works
            </h2>
            <p className="mt-3 text-sm text-neutral-800/70 dark:text-white/60 max-w-2xl">
              A simple flow your board can follow without training sessions or
              messy spreadsheets.
            </p>
          </div>

          <div className="relative flex flex-col gap-6 md:gap-7">
            {/* Timeline spine, tucked just to the left of cards */}
            <div
              aria-hidden="true"
              className="pointer-events-none absolute left-4 top-0 bottom-0 flex justify-center"
            >
              <div className="h-full w-px bg-neutral-300/30 dark:bg-white/10" />
              <div
                data-how-line
                className="absolute inset-y-0 left-0 right-0 m-auto h-full w-[3px] rounded-full bg-emerald-400/80"
              />
            </div>

            {/* Steps column */}
            <div className="flex flex-col gap-4 md:gap-5">
              {[
                {
                  n: "01",
                  title: "Create Organization & Invite Board",
                  desc: "Set up your club, org, or startup and invite all board members and recruiting managers.",
                },
                {
                  n: "02",
                  title: "Set Up Recruitment Cycle & Rounds",
                  desc: "Create a recruitment cycle (semester, year, etc.) and define rounds (interviews, events) with custom metrics.",
                },
                {
                  n: "03",
                  title: "Import Applicants via CSV",
                  desc: "Upload applicants from your form (Google Forms, Tally, etc.) and map their info instantly.",
                },
                {
                  n: "04",
                  title: "Collect Feedback & Scores",
                  desc: "Gather anonymized or named feedback and scores from board and general members for each round.",
                },
                {
                  n: "05",
                  title: "Progress Applicants & Export Decisions",
                  desc: "Move applicants to the next round, mark as accepted/rejected/maybe, and export decisions and emails.",
                },
              ].map((s) => (
                <div key={s.n} className="relative pl-12">
                  <div
                    data-how-step
                    className="relative rounded-2xl border border-black/10 bg-white/70 p-5 md:p-6 shadow-[0_20px_50px_rgba(10,12,14,0.08)] backdrop-blur dark:border-white/12 dark:bg-black/40 dark:shadow-[0_20px_50px_rgba(0,0,0,0.55)]"
                  >
                    {/* Node on the line */}
                    <div className="absolute left-0 top-6 -translate-x-1/2 h-3 w-3 rounded-full border border-emerald-200 bg-white dark:bg-black" />

                    <div className="flex items-start gap-4">
                      <div className="font-display text-sm tracking-[0.22em] text-neutral-900/70 dark:text-white/60">
                        {s.n}
                      </div>
                      <div className="flex-1">
                        <h3 className="font-display text-lg font-semibold text-neutral-950 dark:text-white">
                          {s.title}
                        </h3>
                        <p className="mt-2 text-sm text-neutral-800/70 dark:text-white/65">
                          {s.desc}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </motion.section>
      {/* Features Section (moved after how-it-works) */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        viewport={{ once: true }}
        className="w-full flex justify-center py-14 md:py-20"
      >
        <div className="relative max-w-6xl w-full rounded-3xl p-8 md:p-14 ink-card dark:ink-card-dark">
          <FeaturesSectionWithHoverEffects />
        </div>
      </motion.section>
      {/* CTA Section */}
      <motion.section
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.4 }}
        viewport={{ once: true }}
        className="w-full flex justify-center py-14 md:py-20"
      >
        <div className="relative max-w-3xl w-full mx-auto rounded-3xl p-10 md:p-12 ink-card dark:ink-card-dark flex flex-col items-center text-center">
          <div className="pointer-events-none absolute -left-6 -top-6 h-24 w-24 rounded-2xl border border-black/10 bg-emerald-600/10 rotate-6 dark:border-white/12 dark:bg-emerald-400/10" />
          <div className="pointer-events-none absolute -right-8 -bottom-8 h-28 w-28 rounded-full border border-black/10 bg-black/5 dark:border-white/12 dark:bg-white/5" />
          <h2 className="font-display text-4xl sm:text-5xl font-semibold tracking-tight mb-4 text-neutral-950 dark:text-white">
            Run Your Club or Org Recruitment in One Workspace
          </h2>
          <p className="text-lg text-neutral-800/80 dark:text-white/75 mb-8 max-w-xl">
            Recruitify is built for recruiting chairs and boards who are tired
            of juggling Google Forms, Docs, and spreadsheets. Manage every
            round, discussion, and decision in one place.
          </p>
          <div className="flex flex-col gap-3 w-full max-w-xs">
            <Link
              href="/dash"
              className="cta-primary-dark text-base"
              prefetch={false}
            >
              Get Started
            </Link>
            <Link
              href="#how-it-works"
              className="cta-secondary-dark text-base"
              prefetch={false}
            >
              Learn More
            </Link>
          </div>
        </div>
      </motion.section>
    </>
  );
}

export default function Landing() {
  const [isPastHero, setIsPastHero] = useState(false);

  useEffect(() => {
    const hero = document.getElementById("landing-hero");
    if (!hero) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsPastHero(!entry.isIntersecting);
      },
      { threshold: 0.2 },
    );

    observer.observe(hero);
    return () => observer.disconnect();
  }, []);

  return (
    <div className="relative flex flex-col min-h-screen overflow-x-hidden paper-surface dark:paper-surface-dark paper-texture">
      <header
        className={`fixed inset-x-0 top-0 z-40 transition-colors duration-300 ${
          isPastHero
            ? "bg-black/20 backdrop-blur supports-[backdrop-filter]:bg-black/15 dark:bg-black/28 dark:supports-[backdrop-filter]:bg-black/24"
            : "bg-transparent"
        }`}
      >
        <div className="w-full px-4 md:px-8 lg:px-12 pt-4">
          <Navbar />
        </div>
      </header>
      <main className="relative z-10 flex-1">
        <LandingAnimatedSections />
      </main>
      {/* Footer */}
      <footer className="relative z-10 w-full border-t border-black/10 dark:border-white/12">
        <div className="mx-auto max-w-6xl px-4 md:px-6 py-7 flex flex-col gap-2 sm:flex-row items-center">
          <p className="text-xs text-neutral-900/60 dark:text-white/60">
            &copy; {new Date().getFullYear()} Recruit. All rights reserved.
          </p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            <Link
              href="#"
              className="text-xs hover:underline underline-offset-4 text-neutral-900/70 dark:text-white/70"
              prefetch={false}
            >
              Terms of Service
            </Link>
            <Link
              href="/privacy-policy"
              className="text-xs hover:underline underline-offset-4 text-neutral-900/70 dark:text-white/70"
              prefetch={false}
            >
              Privacy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
